---
apiVersion: cassandra.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: db-conn
      key: credentials
# docker run --rm -p 5432:5432  -e POSTGRES_PASSWORD=pass postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
stringData:
  credentials: |
    {
      "username": "cassandra",
      "password": "cassandra",
      "endpoint": "localhost",
      "port": "9042"
    }
---
apiVersion: cql.cassandra.crossplane.io/v1alpha1
kind: Keyspace
metadata:
  name: something 
spec:
  forProvider: {}
---
apiVersion: cql.cassandra.crossplane.io/v1alpha1
kind: Keyspace
metadata:
  name: otherone 
spec:
  forProvider: {}
---
apiVersion: cql.cassandra.crossplane.io/v1alpha1
kind: Role
metadata:
  name: example-role
spec:
  forProvider:
    privileges:
      superUser: true
      login: true
  writeConnectionSecretToRef:
    name: example-role-pass
    namespace: default
---
apiVersion: cql.cassandra.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant
spec:
  forProvider:
    privileges:
      - SELECT
      - MODIFY
    roleRef:
      name: example-role
    keyspaceRef:
      name: something